apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-web-app
        image: docker.io/manukoli1986/flask-web-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels:
    app: flask-app
spec:
  ports:
    - port: 80
  selector:
    app: flask-app
  type: LoadBalancer
