apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    name: http
    nodePort: 30300
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf # mount nginx-conf volumn to /etc/nginx
          name: nginx-configuration
          subPath: default.conf
      volumes:
      - name: nginx-configuration
        configMap:
          name: nginx-config # place ConfigMap `nginx-conf` on /etc/nginx